"""empty message

Revision ID: b2fd4164159c
Revises: 2e5674eed33b
Create Date: 2018-10-07 14:52:41.002091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fd4164159c'
down_revision = '2e5674eed33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['common_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('common_post', sa.Column('readCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_post', 'readCount')
    op.drop_table('tag')
    # ### end Alembic commands ###
